### ISSUE TITLE
Xamarin Redesign

### ISSUE THREAD

**Issue by sven15** [Integreat/app-cross_platform#67]
![screenshot_20160609-090945](https://cloud.githubusercontent.com/assets/15197000/19548337/37e5d6ee-969e-11e6-88b0-2effaacfa44c.png)
![screenshot_20160609-090948_1024](https://cloud.githubusercontent.com/assets/15197000/19548340/38165c10-969e-11e6-85b2-e2bd75ca41a0.png)
![screenshot_20160609-090951](https://cloud.githubusercontent.com/assets/15197000/19548339/38153510-969e-11e6-9487-041007daffd5.png)
![screenshot_20160609-090955_1024](https://cloud.githubusercontent.com/assets/15197000/19548341/3818a22c-969e-11e6-9f19-7e38e278ad28.png)
![screenshot_20160609-091001_1024](https://cloud.githubusercontent.com/assets/15197000/19548342/38191d74-969e-11e6-90b0-17c7e7b44a77.png)
![screenshot_20160609-091033_1024](https://cloud.githubusercontent.com/assets/15197000/19548343/38197bfc-969e-11e6-95b3-8f656fa5b374.png)
![screenshot_20160609-091045_1024](https://cloud.githubusercontent.com/assets/15197000/19548338/3808f73c-969e-11e6-943c-5d8815f75386.png)
![screenshot_20160609-091055_1024](https://cloud.githubusercontent.com/assets/15197000/19548345/382b48fa-969e-11e6-94f6-8c1838887707.png)
![screenshot_20160609-091126_1024](https://cloud.githubusercontent.com/assets/15197000/19548346/3834963a-969e-11e6-9736-113a93aa6147.png)

**Comment by BerndNK** [comment]
As mentioned at I5K, renamed the issue to Xamarin Redesign.

**Comment by FritjofK** [comment]
First pager AFTER city and language selection: 

1. Change the sliders at the top to: 
Left: Extras 
Middle: Kategorien
Right: News
all strings need be translated to English, French, Arabic, Farsi, Tigrinya, Russian
Start with the middle slide (Kategorien)

2. Put the name of the city into the header (STADTNAME) on this page 

3. Put two "icons" in the top right corner: Search and menu (drop down with "settings", "language") 

![img_1194](https://cloud.githubusercontent.com/assets/16462172/24323288/ae0de4e2-1173-11e7-8563-c7cec0c53caf.JPG)

**Comment by FritjofK** [comment]
2nd and 3rd level together in app: 

Top right: As before
Top Left: Back-Button and name of the selected category 

Top page: show the icon only

After that show the second and third level together (as a block)
An arrow on the second level shows that there is content otherwise no arrow.

![img_1197](https://cloud.githubusercontent.com/assets/16462172/24323460/f1ed6514-1175-11e7-91e1-071dfa73dcd5.JPG)

**Comment by FritjofK** [comment]
After clicking on something in LEFT slider (Extras): 

Top right: only dropdown-menu (no search, a user account symbol will be added later on)
Top left:  Back-button, name of "extra"

Make blocks (as in categories) of each section (1. Jobbörsen, 2. Allgemeines, ...) 
Each jobplattform provider has a logo that needs to be put in. 

![img_1196](https://cloud.githubusercontent.com/assets/16462172/24323546/8a7ce8a8-1177-11e7-97de-35584177682e.JPG)

**Comment by FritjofK** [comment]
News-Slider: 
In CMS will be an option to have push news OR events OR both. 
Push News and events will look the same from a visual point of view (Block with top left News or Event and top right date) und the description below. 

It can be selected in the CMS how many days Push news shall remain. Push new will always stay at the top because they are always in the past (from a date-stamp point of view) 

Events are ordered from the nearest (top) to the most for away (bottom)

![img_1195](https://cloud.githubusercontent.com/assets/16462172/24323668/780582be-1179-11e7-8bad-70c843fed40d.JPG)

**Comment by FritjofK** [comment]
**Scaling and Positioning on first screen**
Position the icons in a way that 8 Icons with text can appear on a screen. Move the text closer to the Icon. 

Screenshot from Stylguide for positions and spacing: 
![grafik](https://cloud.githubusercontent.com/assets/16462172/24458516/710f785c-1499-11e7-82b4-0095319b4dac.png)

**Comment by FritjofK** [comment]
Find a solution to display lists in the same way: 
1. List of cities (probably need to stay on the left side)
2. Language selection (german, english, french on the left side - farsi, arabic on the right side)
3. List view of pages when 2nd and 3rd are shown together (see screenshot from styleguide) 
4. Maybe also show search results the same way. 

Questions: 
What color is the dividing line (yellow or grey)? 

![grafik](https://cloud.githubusercontent.com/assets/16462172/24459277/6c067a02-149b-11e7-92af-095fab8c5f31.png)

**Comment by FritjofK** [comment]
Keep the Stylguide in mind and only break from it when necessary or discussed in Slack or on I7K 
https://drive.google.com/a/integreat-app.de/file/d/0B2UAtDRoGkAeYnZWTDNHWG9uejg/view?usp=sharing

**Comment by dkehne** [comment]
we should close this issue and create smaller issues seperately as far as the bugs are still in there
